// CommonJS, every file is a module (by default)
// Modules - Encapsulated Code (only share minimum )
const { leonardo, castillo } = require('./04-names')
const sayHi = require('./05-utils')
const data = require('./06-alternative-flavor')
require('./07-mind-grenade')
sayHi('Annestesia')
sayHi(leonardo)
sayHi(castillo)